# Generated by Django 4.2.2 on 2023-06-26 11:38

from django.db import migrations, models
import uploadapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileupload',
            name='csv_file',
            field=models.FileField(max_length=600, upload_to=uploadapp.models.get_csv_upload_path),
        ),
    ]
