# Generated by Django 4.2.2 on 2023-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_csvprocessedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvprocessedfile',
            name='proccedfile_path',
            field=models.CharField(max_length=600),
        ),
    ]
