# Generated by Django 4.2.2 on 2023-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_remove_csvfileupload_message_csvfileupload_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileupload',
            name='email',
            field=models.EmailField(default='bg@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
