# Generated by Django 4.2.2 on 2023-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_alter_csvprocessedfile_proccedfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileupload',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
