# Generated by Django 4.2.2 on 2023-07-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_remove_csvprocessedfile_proccedfile_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvprocessedfile',
            old_name='processed_file_path',
            new_name='processed_file',
        ),
        migrations.RemoveField(
            model_name='csvprocessedfile',
            name='file_name',
        ),
    ]
