# Generated by Django 4.2.2 on 2023-06-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_alter_csvfileupload_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfileupload',
            name='upload_status',
        ),
    ]
