# Generated by Django 4.2.2 on 2023-07-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0006_rename_processed_file_path_csvprocessedfile_processed_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvprocessedfile',
            old_name='csv_proccessed_file',
            new_name='csv_processed_file',
        ),
    ]
