# Generated by Django 4.2.2 on 2023-07-03 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0007_rename_csv_proccessed_file_csvprocessedfile_csv_processed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileupload',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
