# Generated by Django 4.2.2 on 2023-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0009_alter_csvfileupload_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileupload',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
