# Generated by Django 4.2.2 on 2023-07-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0010_alter_csvfileupload_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfileupload',
            name='unique_identifier',
        ),
    ]
